id: A80B0EBB0
title: Concise Daily Practice of Vajrasattva
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:14:46.148537
  last_modified_at: 2022-03-01 03:14:46.148544
