id: A80B0EBB0
title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage of Zabtik
  Drolchok'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:14:46.156889
  last_modified_at: 2022-03-01 03:14:46.156892
