id: A80B0EBB0
title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa Lhundrupma)
  from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:14:46.166700
  last_modified_at: 2022-03-01 03:14:46.166703
