id: A80B0EBB0
title: White and Red Sur Offerings That Are Very Easy to Apply
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:14:46.184866
  last_modified_at: 2022-03-01 03:14:46.184869
