id: A80B0EBB0
title: The Testament Prayer to Orgyen Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:14:46.169954
  last_modified_at: 2022-03-01 03:14:46.169957
