id: A80B0EBB0
title: The Single-Page Practice of the Guru of Great Bliss
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:14:46.168039
  last_modified_at: 2022-03-01 03:14:46.168042
