id: A80B0EBB0
title: The Lament of Rudra
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:14:46.157930
  last_modified_at: 2022-03-01 03:14:46.157933
