id: A80B0EBB0
title: Vajrakīla Tsok Prayer from Sangtik Korsum
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:14:46.181503
  last_modified_at: 2022-03-01 03:14:46.181506
