id: A80B0EBB0
title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:14:46.161856
  last_modified_at: 2022-03-01 03:14:46.161859
