id: A80B0EBB0
title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
  of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:14:46.150467
  last_modified_at: 2022-03-01 03:14:46.150471
