id: A80B0EBB0
title: Extremely Secret Unelaborate Daily SÄdhana for the Heart Practice of the Great
  Demon-Slayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:14:46.151719
  last_modified_at: 2022-03-01 03:14:46.151722
