id: A80B0EBB0
title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna as found
  in Padmasambhava’s Sevenfold Cycle of Profundity'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:14:46.178188
  last_modified_at: 2022-03-01 03:14:46.178192
